-- MySQL Script generated by MySQL Workbench
-- Sun Jan 23 17:24:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_perfumes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_perfumes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_perfumes` DEFAULT CHARACTER SET utf8 ;
USE `db_perfumes` ;

-- -----------------------------------------------------
-- Table `db_perfumes`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`generos` (
  `idgeneros` INT NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idgeneros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perfumes`.`tipos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`tipos_usuarios` (
  `idtipos_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipos_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perfumes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `userscol` INT NULL,
  `tipo_usuario` INT NULL,
  `generos_idgeneros` INT NOT NULL,
  `tipos_usuarios_idtipos_usuarios` INT NOT NULL,
  PRIMARY KEY (`idusers`),
  INDEX `fk_users_generos1_idx` (`generos_idgeneros` ASC) VISIBLE,
  INDEX `fk_users_tipos_usuarios1_idx` (`tipos_usuarios_idtipos_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_users_generos1`
    FOREIGN KEY (`generos_idgeneros`)
    REFERENCES `db_perfumes`.`generos` (`idgeneros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_tipos_usuarios1`
    FOREIGN KEY (`tipos_usuarios_idtipos_usuarios`)
    REFERENCES `db_perfumes`.`tipos_usuarios` (`idtipos_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perfumes`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`marcas` (
  `idmarcas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perfumes`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `marcas_idmarcas` INT NOT NULL,
  PRIMARY KEY (`idproducts`),
  INDEX `fk_products_marcas1_idx` (`marcas_idmarcas` ASC) VISIBLE,
  CONSTRAINT `fk_products_marcas1`
    FOREIGN KEY (`marcas_idmarcas`)
    REFERENCES `db_perfumes`.`marcas` (`idmarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_perfumes`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perfumes`.`cantidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`cantidades` (
  `idcantidades` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idcantidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perfumes`.`cantidades_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`cantidades_has_products` (
  `cantidades_idcantidades` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`cantidades_idcantidades`, `products_idproducts`),
  INDEX `fk_cantidades_has_products_products1_idx` (`products_idproducts` ASC) VISIBLE,
  INDEX `fk_cantidades_has_products_cantidades_idx` (`cantidades_idcantidades` ASC) VISIBLE,
  CONSTRAINT `fk_cantidades_has_products_cantidades`
    FOREIGN KEY (`cantidades_idcantidades`)
    REFERENCES `db_perfumes`.`cantidades` (`idcantidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cantidades_has_products_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `db_perfumes`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perfumes`.`categorias_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perfumes`.`categorias_has_products` (
  `categorias_idcategorias` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`categorias_idcategorias`, `products_idproducts`),
  INDEX `fk_categorias_has_products_products1_idx` (`products_idproducts` ASC) VISIBLE,
  INDEX `fk_categorias_has_products_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_has_products_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `db_perfumes`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_has_products_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `db_perfumes`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
